# Thymeleaf cache
spring.thymeleaf.cache=true
spring.web.resources.chain.cache=true

# Puerto de escucha
server.port=8080

# Hibernate: crea y dropea
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:h2:file:./iwdb
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Importador de ficheros SQL multilínea
spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor=\
org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor

# Consola H2 desactivada
spring.h2.console.enabled=false
spring.h2.console.path=/h2

# Configuración de errores
server.error.include-message=never
server.error.include-stacktrace=never

# Logging
logging.level.root=info
logging.level.org.hibernate=info
logging.level.org.springframework.web=debug
logging.level.org.springframework.security=debug

# Ruta base para ficheros de usuario
es.ucm.fdi.base-path=./iwdata

# Flag de debug para Thymeleaf
es.ucm.fdi.debug=false

# Tamaño máximo de subida de ficheros
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
