# Workflow autogenerado por inteligencia artificial
name: Test and Deploy Arena of Music Spring Boot App

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build Spring Boot App
        run: mvn clean package -DskipTests
          
      - name: Run Spring Boot Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test 
    if: github.ref == 'refs/heads/main'

    environment: UCM Docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Configure credentials
        run: |
          echo '{
            "target": "${{ secrets.TARGET }}",
            "target_user": "${{ secrets.TARGET_USER }}",
            "target_pass": "${{ secrets.TARGET_PASS }}",
            "jumphost": "${{ secrets.JUMPHOST }}",
            "jumphost_user": "${{ secrets.JUMPHOST_USER }}",
            "jumphost_pass": "${{ secrets.JUMPHOST_PASS }}"
          }' > credentials.json
      
      - name: Run Deploy Script
        run: |
          source venv/bin/activate
          python deploy.py
      
      - name: Deploy Application in Tmux
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TARGET_USER }}@${{ secrets.TARGET }} << 'EOF'
            echo "Starting the application in tmux..."
            tmux send-keys -t myapp "SPRING_PROFILES_ACTIVE=container java -jar target/*.jar" C-m
          EOF
